2018-04-13 03:38:08 INFO run.py:213 GNS3 server version 2.1.0
2018-04-13 03:38:08 INFO run.py:215 Copyright (c) 2007-2018 GNS3 Technologies Inc.
2018-04-13 03:38:08 INFO run.py:218 Config file C:\Users\user\AppData\Roaming\GNS3\gns3_server.ini loaded
2018-04-13 03:38:08 INFO run.py:218 Config file C:\Program Files\GNS3\gns3_server.ini loaded
2018-04-13 03:38:08 INFO run.py:218 Config file C:\Users\user\AppData\Roaming\GNS3.ini loaded
2018-04-13 03:38:08 INFO run.py:218 Config file %COMMON_APPDATA%\GNS3\gns3_server.ini loaded
2018-04-13 03:38:08 INFO run.py:218 Config file %COMMON_APPDATA%\GNS3.ini loaded
2018-04-13 03:38:08 WARNING run.py:224 Local mode is enabled. Beware, clients will have full control on your filesystem
2018-04-13 03:38:08 INFO run.py:232 Running with Python 3.6.3 and has PID 41672
2018-04-13 03:38:08 INFO web_server.py:270 Starting server on 127.0.0.1:3080
2018-04-13 03:38:08 INFO __init__.py:65 Load controller configuration file C:\Users\user\AppData\Roaming\GNS3\gns3_controller.conf
2018-04-13 03:38:08 INFO __init__.py:143 Start controller
2018-04-13 03:38:08 INFO compute.py:79 Create compute local
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/compute/capabilities HTTP/1.1" 200 498 "-" "Python/3.6 aiohttp/2.2.5"
2018-04-13 03:38:09 INFO __init__.py:275 Start the GNS3 VM
2018-04-13 03:38:09 INFO compute.py:79 Create compute vm
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/version HTTP/1.1" 200 225 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/version HTTP/1.1" 200 225 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/appliances/templates HTTP/1.1" 200 447600 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/appliances HTTP/1.1" 200 5296 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/computes HTTP/1.1" 200 1297 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/projects HTTP/1.1" 200 182 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/projects HTTP/1.1" 200 182 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/symbols/%3A/symbols/vpcs_guest.svg/raw HTTP/1.1" 200 19494 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/symbols/%3A/symbols/qemu_guest.svg/raw HTTP/1.1" 200 45561 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/symbols/%3A/symbols/router.svg/raw HTTP/1.1" 200 11036 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/symbols/%3A/symbols/vmware_guest.svg/raw HTTP/1.1" 200 20015 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/symbols/%3A/symbols/cloud.svg/raw HTTP/1.1" 200 27981 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/symbols/%3A/symbols/ethernet_switch.svg/raw HTTP/1.1" 200 9272 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/symbols/%3A/symbols/hub.svg/raw HTTP/1.1" 200 7635 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/symbols/%3A/symbols/frame_relay_switch.svg/raw HTTP/1.1" 200 10026 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/symbols/%3A/symbols/atm_switch.svg/raw HTTP/1.1" 200 9958 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/symbols/loadbalancer.svg/raw HTTP/1.1" 200 18842 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/symbols/linux_guest.svg/raw HTTP/1.1" 200 18842 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/symbols/%3A/symbols/multilayer_switch.svg/raw HTTP/1.1" 200 21516 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/symbols/%3A/symbols/guest.svg/raw HTTP/1.1" 200 18842 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/symbols/%3A/symbols/firewall.svg/raw HTTP/1.1" 200 9625 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/symbols/%3A/symbols/asa.svg/raw HTTP/1.1" 200 18811 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/symbols/mgmt_station.svg/raw HTTP/1.1" 200 18842 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/symbols/cisco-fmcv.svg/raw HTTP/1.1" 200 18842 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/symbols/cisco-ise.svg/raw HTTP/1.1" 200 18842 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/symbols/%3A/symbols/ids.svg/raw HTTP/1.1" 200 13372 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/symbols/firefox.svg/raw HTTP/1.1" 200 18842 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/symbols/fortinet.svg/raw HTTP/1.1" 200 18842 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/symbols/juniper-vmx.svg/raw HTTP/1.1" 200 18842 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/symbols/juniper-vqfx.svg/raw HTTP/1.1" 200 18842 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/symbols/%3A/symbols/router_firewall.svg/raw HTTP/1.1" 200 50060 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/symbols/mgmt_station_docker.svg/raw HTTP/1.1" 200 18842 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/symbols/%3A/symbols/wlan_controller.svg/raw HTTP/1.1" 200 261469 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/symbols/ostinato-3d-icon.svg/raw HTTP/1.1" 200 18842 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/symbols/pan-vm-fw.svg/raw HTTP/1.1" 200 18842 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/symbols/vRIN.svg/raw HTTP/1.1" 200 18842 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:09 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:09 +0000] "GET /v2/symbols/microsoft.svg/raw HTTP/1.1" 200 18842 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:14 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:14 +0000] "GET /v2/computes HTTP/1.1" 200 1296 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:16 INFO __init__.py:574 Searching for VMware VMs in inventory file "C:\Users\user\AppData\Roaming\Vmware\Inventory.vmls"
2018-04-13 03:38:16 INFO __init__.py:390 Executing vmrun with command: 'C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe' -T ws checkToolsState 'C:\Users\user\Documents\Virtual Machines\GNS3 VM\GNS3 VM.vmx'
2018-04-13 03:38:16 INFO __init__.py:390 Executing vmrun with command: 'C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe' -T ws list
2018-04-13 03:38:16 INFO vmware_gns3_vm.py:150 Update GNS3 VM settings
2018-04-13 03:38:16 INFO vmware_gns3_vm.py:84 GNS3 VM vCPU count set to 4 and RAM amount set to 2048
2018-04-13 03:38:16 INFO __init__.py:390 Executing vmrun with command: 'C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe' -T ws start 'C:\Users\user\Documents\Virtual Machines\GNS3 VM\GNS3 VM.vmx'
2018-04-13 03:38:18 INFO vmware_gns3_vm.py:160 GNS3 VM has been started
2018-04-13 03:38:18 INFO vmware_gns3_vm.py:165 Waiting for GNS3 VM IP
2018-04-13 03:38:19 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:19 +0000] "GET /v2/computes HTTP/1.1" 200 1297 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:23 INFO vmware_gns3_vm.py:179 GNS3 VM IP address set to 192.168.159.128
2018-04-13 03:38:24 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:24 +0000] "GET /v2/computes HTTP/1.1" 200 1298 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:25 INFO project.py:80 Project b45a278f-6717-4abd-8d7f-68d7345d308a with path 'F:\Õ»– À¿¡¿\PENTEST LAB PROJECT DNS\PENTEST lab project' created
2018-04-13 03:38:25 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:25 +0000] "POST /v2/compute/projects HTTP/1.1" 201 289 "-" "Python/3.6 aiohttp/2.2.5"
2018-04-13 03:38:25 INFO vmware_vm.py:673 VMware VM 'Ubuntu_WEB' [657d5cdf-dc73-4197-ab79-d5fdb81b9687] has changed the number of Ethernet adapters to 1
2018-04-13 03:38:25 INFO vmware_vm.py:717 VMware VM 'Ubuntu_WEB' [657d5cdf-dc73-4197-ab79-d5fdb81b9687] is allowed to use any adapter
2018-04-13 03:38:25 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:25 +0000] "POST /v2/compute/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/vmware/nodes HTTP/1.1" 201 922 "-" "Python/3.6 aiohttp/2.2.5"
2018-04-13 03:38:25 INFO vmware_vm.py:673 VMware VM 'vTiger_CRM' [e01ad6a6-b018-4197-9062-a8f6c82dd5af] has changed the number of Ethernet adapters to 1
2018-04-13 03:38:25 INFO vmware_vm.py:717 VMware VM 'vTiger_CRM' [e01ad6a6-b018-4197-9062-a8f6c82dd5af] is allowed to use any adapter
2018-04-13 03:38:25 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:25 +0000] "POST /v2/compute/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/vmware/nodes HTTP/1.1" 201 926 "-" "Python/3.6 aiohttp/2.2.5"
2018-04-13 03:38:25 INFO vmware_vm.py:673 VMware VM 'Ubuntu_12.04.5_Web' [967c3419-71da-4d5f-a3a5-8227b47387bd] has changed the number of Ethernet adapters to 1
2018-04-13 03:38:25 INFO vmware_vm.py:717 VMware VM 'Ubuntu_12.04.5_Web' [967c3419-71da-4d5f-a3a5-8227b47387bd] is allowed to use any adapter
2018-04-13 03:38:25 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:25 +0000] "POST /v2/compute/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/vmware/nodes HTTP/1.1" 201 940 "-" "Python/3.6 aiohttp/2.2.5"
2018-04-13 03:38:25 INFO vmware_vm.py:673 VMware VM 'WindowsServer2012-3' [ce7ba5c4-477f-4c8f-b943-325997e1812a] has changed the number of Ethernet adapters to 1
2018-04-13 03:38:25 INFO vmware_vm.py:717 VMware VM 'WindowsServer2012-3' [ce7ba5c4-477f-4c8f-b943-325997e1812a] is allowed to use any adapter
2018-04-13 03:38:25 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:25 +0000] "POST /v2/compute/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/vmware/nodes HTTP/1.1" 201 946 "-" "Python/3.6 aiohttp/2.2.5"
2018-04-13 03:38:25 INFO base_node.py:537 Starting new uBridge hypervisor 127.0.0.1:62529
2018-04-13 03:38:25 INFO hypervisor.py:163 starting ubridge: ['C:\\Program Files\\GNS3\\ubridge.EXE', '-H', '127.0.0.1:62529']
2018-04-13 03:38:25 INFO hypervisor.py:165 logging to F:\Õ»– À¿¡¿\PENTEST LAB PROJECT DNS\PENTEST lab project\project-files\builtin\cac0d67f-3637-4573-862a-7ae8a8f25bba\ubridge.log
2018-04-13 03:38:25 INFO hypervisor.py:173 ubridge started PID=9104
2018-04-13 03:38:25 INFO base_node.py:540 Hypervisor 127.0.0.1:62529 has successfully started
2018-04-13 03:38:26 INFO ubridge_hypervisor.py:84 Connected to uBridge hypervisor after 0.5140 seconds
2018-04-13 03:38:26 INFO cloud.py:128 Cloud "Cloud-1" [cac0d67f-3637-4573-862a-7ae8a8f25bba] has been created
2018-04-13 03:38:26 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:26 +0000] "POST /v2/compute/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/cloud/nodes HTTP/1.1" 201 2142 "-" "Python/3.6 aiohttp/2.2.5"
2018-04-13 03:38:27 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:27 +0000] "GET /v2/compute/network/interfaces HTTP/1.1" 200 2900 "-" "Python/3.6 aiohttp/2.2.5"
2018-04-13 03:38:27 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:27 +0000] "POST /v2/compute/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/ports/udp HTTP/1.1" 201 242 "-" "Python/3.6 aiohttp/2.2.5"
2018-04-13 03:38:27 INFO vmware_vm.py:754 VMware VM 'Ubuntu_WEB' [657d5cdf-dc73-4197-ab79-d5fdb81b9687]: NIO UDP added to adapter 0
2018-04-13 03:38:27 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:27 +0000] "POST /v2/compute/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/vmware/nodes/657d5cdf-dc73-4197-ab79-d5fdb81b9687/adapters/0/ports/0/nio HTTP/1.1" 201 385 "-" "Python/3.6 aiohttp/2.2.5"
2018-04-13 03:38:27 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:27 +0000] "POST /v2/compute/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/ports/udp HTTP/1.1" 201 242 "-" "Python/3.6 aiohttp/2.2.5"
2018-04-13 03:38:27 INFO vmware_vm.py:754 VMware VM 'vTiger_CRM' [e01ad6a6-b018-4197-9062-a8f6c82dd5af]: NIO UDP added to adapter 0
2018-04-13 03:38:27 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:27 +0000] "POST /v2/compute/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/vmware/nodes/e01ad6a6-b018-4197-9062-a8f6c82dd5af/adapters/0/ports/0/nio HTTP/1.1" 201 385 "-" "Python/3.6 aiohttp/2.2.5"
2018-04-13 03:38:27 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:27 +0000] "POST /v2/compute/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/ports/udp HTTP/1.1" 201 242 "-" "Python/3.6 aiohttp/2.2.5"
2018-04-13 03:38:27 INFO vmware_vm.py:754 VMware VM 'Ubuntu_12.04.5_Web' [967c3419-71da-4d5f-a3a5-8227b47387bd]: NIO UDP added to adapter 0
2018-04-13 03:38:27 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:27 +0000] "POST /v2/compute/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/vmware/nodes/967c3419-71da-4d5f-a3a5-8227b47387bd/adapters/0/ports/0/nio HTTP/1.1" 201 385 "-" "Python/3.6 aiohttp/2.2.5"
2018-04-13 03:38:27 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:27 +0000] "POST /v2/compute/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/ports/udp HTTP/1.1" 201 242 "-" "Python/3.6 aiohttp/2.2.5"
2018-04-13 03:38:27 INFO vmware_vm.py:754 VMware VM 'WindowsServer2012-3' [ce7ba5c4-477f-4c8f-b943-325997e1812a]: NIO UDP added to adapter 0
2018-04-13 03:38:27 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:27 +0000] "POST /v2/compute/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/vmware/nodes/ce7ba5c4-477f-4c8f-b943-325997e1812a/adapters/0/ports/0/nio HTTP/1.1" 201 385 "-" "Python/3.6 aiohttp/2.2.5"
2018-04-13 03:38:27 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:27 +0000] "POST /v2/compute/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/ports/udp HTTP/1.1" 201 242 "-" "Python/3.6 aiohttp/2.2.5"
2018-04-13 03:38:27 INFO cloud.py:302 Cloud "Cloud-1" [cac0d67f-3637-4573-862a-7ae8a8f25bba]: NIO NIO UDP bound to port 0
2018-04-13 03:38:27 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:27 +0000] "POST /v2/compute/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/cloud/nodes/cac0d67f-3637-4573-862a-7ae8a8f25bba/adapters/0/ports/0/nio HTTP/1.1" 201 384 "-" "Python/3.6 aiohttp/2.2.5"
2018-04-13 03:38:28 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:28 +0000] "POST /v2/projects/load HTTP/1.1" 201 718 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:28 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:28 +0000] "GET /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/nodes HTTP/1.1" 200 35466 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:29 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:29 +0000] "GET /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/links HTTP/1.1" 200 13022 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:29 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:29 +0000] "GET /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/drawings HTTP/1.1" 200 204 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:30 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:30 +0000] "GET /v2/computes HTTP/1.1" 200 1709 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:35 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:35 +0000] "POST /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/nodes/964f5239-88fc-4e0f-a34a-1b318527065d/start HTTP/1.1" 201 2789 "-" "GNS3 QT Client v2.1.0"
2018-04-13 03:38:36 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:00:38:36 +0000] "POST /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/nodes/477e1f38-ca35-4e3d-a429-4095d631e656/start HTTP/1.1" 201 2516 "-" "GNS3 QT Client v2.1.0"
2018-04-13 04:17:56 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:01:17:56 +0000] "GET /v2/computes HTTP/1.1" 200 1708 "-" "GNS3 QT Client v2.1.0"
2018-04-13 06:22:27 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:03:22:27 +0000] "GET /v2/computes HTTP/1.1" 200 1708 "-" "GNS3 QT Client v2.1.0"
2018-04-13 07:22:35 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:04:22:35 +0000] "POST /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/links/6cba9f2b-b5fa-46ee-ab5b-a6f7fd341e58/start_capture HTTP/1.1" 201 1587 "-" "GNS3 QT Client v2.1.0"
2018-04-13 07:22:42 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:04:22:42 +0000] "POST /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/links/d7f182ea-2782-44cb-86bc-4289bd6b8f44/start_capture HTTP/1.1" 201 1570 "-" "GNS3 QT Client v2.1.0"
2018-04-13 07:22:52 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:04:22:52 +0000] "POST /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/links/d7f182ea-2782-44cb-86bc-4289bd6b8f44/stop_capture HTTP/1.1" 201 1570 "-" "GNS3 QT Client v2.1.0"
2018-04-13 07:22:53 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:04:22:53 +0000] "POST /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/links/6cba9f2b-b5fa-46ee-ab5b-a6f7fd341e58/stop_capture HTTP/1.1" 201 1587 "-" "GNS3 QT Client v2.1.0"
2018-04-13 07:22:58 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:04:22:58 +0000] "POST /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/links/d7f182ea-2782-44cb-86bc-4289bd6b8f44/start_capture HTTP/1.1" 201 1570 "-" "GNS3 QT Client v2.1.0"
2018-04-13 07:23:21 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:04:23:21 +0000] "POST /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/links/d7f182ea-2782-44cb-86bc-4289bd6b8f44/stop_capture HTTP/1.1" 201 1570 "-" "GNS3 QT Client v2.1.0"
2018-04-13 08:59:20 INFO __init__.py:390 Executing vmrun with command: 'C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe' -T ws list
2018-04-13 08:59:20 INFO base_node.py:537 Starting new uBridge hypervisor 127.0.0.1:51496
2018-04-13 08:59:20 INFO hypervisor.py:163 starting ubridge: ['C:\\Program Files\\GNS3\\ubridge.EXE', '-H', '127.0.0.1:51496']
2018-04-13 08:59:20 INFO hypervisor.py:165 logging to F:\Õ»– À¿¡¿\PENTEST LAB PROJECT DNS\PENTEST lab project\project-files\vmware\e01ad6a6-b018-4197-9062-a8f6c82dd5af\ubridge.log
2018-04-13 08:59:20 INFO hypervisor.py:173 ubridge started PID=38692
2018-04-13 08:59:20 INFO base_node.py:540 Hypervisor 127.0.0.1:51496 has successfully started
2018-04-13 08:59:20 INFO ubridge_hypervisor.py:84 Connected to uBridge hypervisor after 0.0120 seconds
2018-04-13 08:59:20 INFO __init__.py:390 Executing vmrun with command: 'C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe' -T ws start 'F:\Õ»– À¿¡¿\PENTEST LAB PROJECT DNS\PENTEST lab hosts vmx\Ubuntu server VRM\Ubuntu 64-bit.vmx'
2018-04-13 08:59:36 INFO base_node.py:667 PCAP filter applied on "VMnet2" for source MAC 00:50:56:C0:00:02
2018-04-13 08:59:36 INFO vmware_vm.py:472 VMware VM 'vTiger_CRM' [e01ad6a6-b018-4197-9062-a8f6c82dd5af] started
2018-04-13 08:59:36 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:05:59:36 +0000] "POST /v2/compute/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/vmware/nodes/e01ad6a6-b018-4197-9062-a8f6c82dd5af/start HTTP/1.1" 204 246 "-" "Python/3.6 aiohttp/2.2.5"
2018-04-13 08:59:36 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:05:59:36 +0000] "POST /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/nodes/e01ad6a6-b018-4197-9062-a8f6c82dd5af/start HTTP/1.1" 201 1826 "-" "GNS3 QT Client v2.1.0"
2018-04-13 09:15:13 ERROR base_events.py:1260 Task exception was never retrieved
future: <Task finished coro=<AsyncioTelnetServer.run() done, defined at ./gns3-server\gns3server\utils\asyncio\telnet_server.py:188> exception=error(109, 'PeekNamedPipe', ' ‡Ì‡Î ·˚Î Á‡Í˚Ú.')>
Traceback (most recent call last):
  File "./gns3-server\gns3server\utils\asyncio\telnet_server.py", line 197, in run
  File "./gns3-server\gns3server\utils\asyncio\telnet_server.py", line 253, in _process
  File "./gns3-server\gns3server\utils\asyncio\serial.py", line 77, in read
pywintypes.error: (109, 'PeekNamedPipe', ' ‡Ì‡Î ·˚Î Á‡Í˚Ú.')
2018-04-13 09:15:50 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:15:50 +0000] "PUT /v2/compute/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/vmware/nodes/e01ad6a6-b018-4197-9062-a8f6c82dd5af HTTP/1.1" 200 931 "-" "Python/3.6 aiohttp/2.2.5"
2018-04-13 09:15:51 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:15:51 +0000] "PUT /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/nodes/e01ad6a6-b018-4197-9062-a8f6c82dd5af HTTP/1.1" 200 1815 "-" "GNS3 QT Client v2.1.0"
2018-04-13 09:15:51 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:15:51 +0000] "PUT /v2/compute/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/vmware/nodes/e01ad6a6-b018-4197-9062-a8f6c82dd5af HTTP/1.1" 200 931 "-" "Python/3.6 aiohttp/2.2.5"
2018-04-13 09:15:51 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:15:51 +0000] "PUT /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/nodes/e01ad6a6-b018-4197-9062-a8f6c82dd5af HTTP/1.1" 200 1815 "-" "GNS3 QT Client v2.1.0"
2018-04-13 09:15:56 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:15:56 +0000] "PUT /v2/compute/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/vmware/nodes/e01ad6a6-b018-4197-9062-a8f6c82dd5af HTTP/1.1" 200 931 "-" "Python/3.6 aiohttp/2.2.5"
2018-04-13 09:15:56 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:15:56 +0000] "PUT /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/nodes/e01ad6a6-b018-4197-9062-a8f6c82dd5af HTTP/1.1" 200 1814 "-" "GNS3 QT Client v2.1.0"
2018-04-13 09:15:57 ERROR base_events.py:1260 Task exception was never retrieved
future: <Task finished coro=<AsyncioTelnetServer.run() done, defined at ./gns3-server\gns3server\utils\asyncio\telnet_server.py:188> exception=error(232, 'WriteFile', '»‰ÂÚ Á‡Í˚ÚËÂ Í‡Ì‡Î‡.')>
Traceback (most recent call last):
  File "./gns3-server\gns3server\utils\asyncio\telnet_server.py", line 197, in run
  File "./gns3-server\gns3server\utils\asyncio\telnet_server.py", line 270, in _process
  File "./gns3-server\gns3server\utils\asyncio\serial.py", line 88, in write
pywintypes.error: (232, 'WriteFile', '»‰ÂÚ Á‡Í˚ÚËÂ Í‡Ì‡Î‡.')
2018-04-13 09:30:56 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:30:56 +0000] "POST /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/nodes/964f5239-88fc-4e0f-a34a-1b318527065d/stop HTTP/1.1" 201 2788 "-" "GNS3 QT Client v2.1.0"
2018-04-13 09:30:59 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:30:59 +0000] "POST /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/nodes/964f5239-88fc-4e0f-a34a-1b318527065d/start HTTP/1.1" 201 2789 "-" "GNS3 QT Client v2.1.0"
2018-04-13 09:33:26 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:33:26 +0000] "PUT /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/nodes/964f5239-88fc-4e0f-a34a-1b318527065d HTTP/1.1" 200 2778 "-" "GNS3 QT Client v2.1.0"
2018-04-13 09:33:30 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:33:30 +0000] "DELETE /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/links/60d6e4d6-36f2-4c4d-ac58-1f7d199f1c63 HTTP/1.1" 204 225 "-" "GNS3 QT Client v2.1.0"
2018-04-13 09:34:07 INFO cloud.py:363 Cloud "Cloud-1" [cac0d67f-3637-4573-862a-7ae8a8f25bba]: NIO NIO UDP removed from port 0
2018-04-13 09:34:07 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:34:07 +0000] "DELETE /v2/compute/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/cloud/nodes/cac0d67f-3637-4573-862a-7ae8a8f25bba/adapters/0/ports/0/nio HTTP/1.1" 204 297 "-" "Python/3.6 aiohttp/2.2.5"
2018-04-13 09:34:07 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:34:07 +0000] "PUT /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/nodes/964f5239-88fc-4e0f-a34a-1b318527065d HTTP/1.1" 200 2780 "-" "GNS3 QT Client v2.1.0"
2018-04-13 09:34:07 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:34:07 +0000] "DELETE /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/links/b929ba23-98c1-4b41-9c4a-a1843bc0bb94 HTTP/1.1" 204 225 "-" "GNS3 QT Client v2.1.0"
2018-04-13 09:34:24 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:34:24 +0000] "POST /v2/compute/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/ports/udp HTTP/1.1" 201 242 "-" "Python/3.6 aiohttp/2.2.5"
2018-04-13 09:34:24 INFO cloud.py:302 Cloud "Cloud-1" [cac0d67f-3637-4573-862a-7ae8a8f25bba]: NIO NIO UDP bound to port 0
2018-04-13 09:34:24 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:34:24 +0000] "POST /v2/compute/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/cloud/nodes/cac0d67f-3637-4573-862a-7ae8a8f25bba/adapters/0/ports/0/nio HTTP/1.1" 201 384 "-" "Python/3.6 aiohttp/2.2.5"
2018-04-13 09:34:24 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:34:24 +0000] "POST /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/links HTTP/1.1" 201 1219 "-" "GNS3 QT Client v2.1.0"
2018-04-13 09:34:24 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:34:24 +0000] "PUT /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/links/3658763a-cc3d-4a9d-9393-d18bbf1f967b HTTP/1.1" 201 1439 "-" "GNS3 QT Client v2.1.0"
2018-04-13 09:34:24 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:34:24 +0000] "PUT /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/links/3658763a-cc3d-4a9d-9393-d18bbf1f967b HTTP/1.1" 201 1495 "-" "GNS3 QT Client v2.1.0"
2018-04-13 09:34:47 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:34:47 +0000] "DELETE /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/links/d7f182ea-2782-44cb-86bc-4289bd6b8f44 HTTP/1.1" 204 225 "-" "GNS3 QT Client v2.1.0"
2018-04-13 09:34:55 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:34:55 +0000] "POST /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/links HTTP/1.1" 201 1219 "-" "GNS3 QT Client v2.1.0"
2018-04-13 09:34:55 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:34:55 +0000] "PUT /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/links/5256e37e-b99b-4393-b5e6-5e0906343de8 HTTP/1.1" 201 1284 "-" "GNS3 QT Client v2.1.0"
2018-04-13 09:34:55 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:34:55 +0000] "PUT /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/links/5256e37e-b99b-4393-b5e6-5e0906343de8 HTTP/1.1" 201 1336 "-" "GNS3 QT Client v2.1.0"
2018-04-13 09:35:04 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:35:04 +0000] "POST /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/nodes/964f5239-88fc-4e0f-a34a-1b318527065d/reload HTTP/1.1" 201 2792 "-" "GNS3 QT Client v2.1.0"
2018-04-13 09:44:55 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:44:55 +0000] "PUT /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/nodes/0d208c22-44dd-4323-985e-abc9fb496fe0 HTTP/1.1" 200 4589 "-" "GNS3 QT Client v2.1.0"
2018-04-13 09:55:06 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:55:06 +0000] "PUT /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/nodes/964f5239-88fc-4e0f-a34a-1b318527065d HTTP/1.1" 200 2782 "-" "GNS3 QT Client v2.1.0"
2018-04-13 09:55:11 INFO cloud.py:363 Cloud "Cloud-1" [cac0d67f-3637-4573-862a-7ae8a8f25bba]: NIO NIO UDP removed from port 0
2018-04-13 09:55:11 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:55:11 +0000] "DELETE /v2/compute/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/cloud/nodes/cac0d67f-3637-4573-862a-7ae8a8f25bba/adapters/0/ports/0/nio HTTP/1.1" 204 297 "-" "Python/3.6 aiohttp/2.2.5"
2018-04-13 09:55:11 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:55:11 +0000] "DELETE /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/links/3658763a-cc3d-4a9d-9393-d18bbf1f967b HTTP/1.1" 204 225 "-" "GNS3 QT Client v2.1.0"
2018-04-13 09:55:13 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:55:13 +0000] "DELETE /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/links/5256e37e-b99b-4393-b5e6-5e0906343de8 HTTP/1.1" 204 225 "-" "GNS3 QT Client v2.1.0"
2018-04-13 09:55:30 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:55:30 +0000] "POST /v2/compute/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/ports/udp HTTP/1.1" 201 242 "-" "Python/3.6 aiohttp/2.2.5"
2018-04-13 09:55:30 INFO cloud.py:302 Cloud "Cloud-1" [cac0d67f-3637-4573-862a-7ae8a8f25bba]: NIO NIO UDP bound to port 0
2018-04-13 09:55:30 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:55:30 +0000] "POST /v2/compute/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/cloud/nodes/cac0d67f-3637-4573-862a-7ae8a8f25bba/adapters/0/ports/0/nio HTTP/1.1" 201 384 "-" "Python/3.6 aiohttp/2.2.5"
2018-04-13 09:55:30 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:55:30 +0000] "POST /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/links HTTP/1.1" 201 1219 "-" "GNS3 QT Client v2.1.0"
2018-04-13 09:55:30 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:55:30 +0000] "PUT /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/links/046a2a3f-4bdf-4d16-ac74-e80464810516 HTTP/1.1" 201 1440 "-" "GNS3 QT Client v2.1.0"
2018-04-13 09:55:30 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:55:30 +0000] "PUT /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/links/046a2a3f-4bdf-4d16-ac74-e80464810516 HTTP/1.1" 201 1493 "-" "GNS3 QT Client v2.1.0"
2018-04-13 09:56:48 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:56:48 +0000] "PUT /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/nodes/0d208c22-44dd-4323-985e-abc9fb496fe0 HTTP/1.1" 200 4589 "-" "GNS3 QT Client v2.1.0"
2018-04-13 09:56:50 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:06:56:50 +0000] "PUT /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/nodes/0d208c22-44dd-4323-985e-abc9fb496fe0 HTTP/1.1" 200 4589 "-" "GNS3 QT Client v2.1.0"
2018-04-13 11:08:43 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:08:08:43 +0000] "POST /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/nodes/964f5239-88fc-4e0f-a34a-1b318527065d/stop HTTP/1.1" 201 2792 "-" "GNS3 QT Client v2.1.0"
2018-04-13 13:07:53 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:10:07:53 +0000] "POST /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/nodes/477e1f38-ca35-4e3d-a429-4095d631e656/stop HTTP/1.1" 201 2515 "-" "GNS3 QT Client v2.1.0"
2018-04-13 13:08:24 INFO base_node.py:550 Stopping uBridge hypervisor 127.0.0.1:51496
2018-04-13 13:08:24 INFO hypervisor.py:197 Stopping uBridge process PID=38692
2018-04-13 13:08:24 INFO __init__.py:390 Executing vmrun with command: 'C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe' -T ws list
2018-04-13 13:08:24 INFO vmware_vm.py:517 VMware VM 'vTiger_CRM' [e01ad6a6-b018-4197-9062-a8f6c82dd5af] stopped
2018-04-13 13:08:24 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:10:08:24 +0000] "POST /v2/compute/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/vmware/nodes/e01ad6a6-b018-4197-9062-a8f6c82dd5af/stop HTTP/1.1" 204 245 "-" "Python/3.6 aiohttp/2.2.5"
2018-04-13 13:08:24 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:10:08:24 +0000] "POST /v2/projects/b45a278f-6717-4abd-8d7f-68d7345d308a/nodes/e01ad6a6-b018-4197-9062-a8f6c82dd5af/stop HTTP/1.1" 201 1824 "-" "GNS3 QT Client v2.1.0"
2018-04-13 13:08:28 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:10:08:28 +0000] "GET /v2/computes HTTP/1.1" 200 1708 "-" "GNS3 QT Client v2.1.0"
2018-04-13 13:10:04 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:10:10:04 +0000] "GET /v2/gns3vm HTTP/1.1" 200 332 "-" "GNS3 QT Client v2.1.0"
2018-04-13 13:10:05 INFO __init__.py:65 Load controller configuration file C:\Users\user\AppData\Roaming\GNS3\gns3_controller.conf
2018-04-13 13:10:05 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:10:10:05 +0000] "GET /v2/gns3vm/engines HTTP/1.1" 200 1293 "-" "GNS3 QT Client v2.1.0"
2018-04-13 13:10:05 INFO __init__.py:574 Searching for VMware VMs in inventory file "C:\Users\user\AppData\Roaming\Vmware\Inventory.vmls"
2018-04-13 13:10:05 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:10:10:05 +0000] "GET /v2/gns3vm/engines/vmware/vms HTTP/1.1" 200 500 "-" "GNS3 QT Client v2.1.0"
2018-04-13 13:13:30 ERROR route.py:205 Controller error detected: <class 'gns3server.controller.compute.ComputeError'>
Traceback (most recent call last):
  File "C:\Python36-x64\lib\site-packages\aiohttp\connector.py", line 710, in _create_direct_connection
  File "C:\Python36-x64\lib\asyncio\base_events.py", line 777, in create_connection
  File "C:\Python36-x64\lib\asyncio\base_events.py", line 764, in create_connection
  File "C:\Python36-x64\lib\asyncio\windows_events.py", line 702, in _poll
  File "C:\Python36-x64\lib\asyncio\windows_events.py", line 514, in finish_connect
OSError: [WinError 121] œÂ‚˚¯ÂÌ Ú‡ÈÏ‡ÛÚ ÒÂÏ‡ÙÓ‡

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python36-x64\lib\site-packages\aiohttp\connector.py", line 378, in connect
  File "C:\Python36-x64\lib\site-packages\aiohttp\connector.py", line 687, in _create_connection
  File "C:\Python36-x64\lib\site-packages\aiohttp\connector.py", line 737, in _create_direct_connection
aiohttp.client_exceptions.ClientConnectorError: [Errno 22] Can not connect to 192.168.159.128:3080 [œÂ‚˚¯ÂÌ Ú‡ÈÏ‡ÛÚ ÒÂÏ‡ÙÓ‡]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./gns3-server\gns3server\controller\compute.py", line 509, in _run_http_query
  File "C:\Python36-x64\lib\site-packages\aiohttp\helpers.py", line 97, in __iter__
  File "C:\Python36-x64\lib\site-packages\aiohttp\client.py", line 231, in _request
  File "C:\Python36-x64\lib\site-packages\aiohttp\connector.py", line 383, in connect
aiohttp.client_exceptions.ClientConnectorError: [Errno 22] Cannot connect to host 192.168.159.128:3080 ssl:False [Can not connect to 192.168.159.128:3080 [œÂ‚˚¯ÂÌ Ú‡ÈÏ‡ÛÚ ÒÂÏ‡ÙÓ‡]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./gns3-server\gns3server\web\route.py", line 195, in control_schema
  File "./gns3-server\gns3server\handlers\api\controller\compute_handler.py", line 138, in get_forward
  File "./gns3-server\gns3server\controller\compute.py", line 588, in forward
  File "./gns3-server\gns3server\controller\compute.py", line 371, in http_query
  File "./gns3-server\gns3server\controller\compute.py", line 513, in _run_http_query
gns3server.controller.compute.ComputeError: [Errno 22] Cannot connect to host 192.168.159.128:3080 ssl:False [Can not connect to 192.168.159.128:3080 [œÂ‚˚¯ÂÌ Ú‡ÈÏ‡ÛÚ ÒÂÏ‡ÙÓ‡]]
2018-04-13 13:13:30 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:10:13:30 +0000] "GET /v2/computes/vm/qemu/binaries HTTP/1.1" 409 513 "-" "GNS3 QT Client v2.1.0"
2018-04-13 13:13:34 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:10:13:34 +0000] "POST /v2/settings HTTP/1.1" 201 10205 "-" "GNS3 QT Client v2.1.0"
2018-04-13 13:13:34 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:10:13:34 +0000] "GET /v2/appliances/templates HTTP/1.1" 200 447600 "-" "GNS3 QT Client v2.1.0"
2018-04-13 13:13:34 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:10:13:34 +0000] "GET /v2/appliances HTTP/1.1" 200 5296 "-" "GNS3 QT Client v2.1.0"
2018-04-13 13:13:38 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:10:13:38 +0000] "GET /v2/gns3vm HTTP/1.1" 200 332 "-" "GNS3 QT Client v2.1.0"
2018-04-13 13:13:38 INFO __init__.py:65 Load controller configuration file C:\Users\user\AppData\Roaming\GNS3\gns3_controller.conf
2018-04-13 13:13:38 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:10:13:38 +0000] "GET /v2/gns3vm/engines HTTP/1.1" 200 1293 "-" "GNS3 QT Client v2.1.0"
2018-04-13 13:13:38 INFO __init__.py:574 Searching for VMware VMs in inventory file "C:\Users\user\AppData\Roaming\Vmware\Inventory.vmls"
2018-04-13 13:13:38 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:10:13:38 +0000] "GET /v2/gns3vm/engines/vmware/vms HTTP/1.1" 200 500 "-" "GNS3 QT Client v2.1.0"
2018-04-13 13:14:05 ERROR route.py:205 Controller error detected: <class 'gns3server.controller.compute.ComputeError'>
Traceback (most recent call last):
  File "C:\Python36-x64\lib\site-packages\aiohttp\connector.py", line 710, in _create_direct_connection
  File "C:\Python36-x64\lib\asyncio\base_events.py", line 777, in create_connection
  File "C:\Python36-x64\lib\asyncio\base_events.py", line 764, in create_connection
  File "C:\Python36-x64\lib\asyncio\windows_events.py", line 702, in _poll
  File "C:\Python36-x64\lib\asyncio\windows_events.py", line 514, in finish_connect
OSError: [WinError 121] œÂ‚˚¯ÂÌ Ú‡ÈÏ‡ÛÚ ÒÂÏ‡ÙÓ‡

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python36-x64\lib\site-packages\aiohttp\connector.py", line 378, in connect
  File "C:\Python36-x64\lib\site-packages\aiohttp\connector.py", line 687, in _create_connection
  File "C:\Python36-x64\lib\site-packages\aiohttp\connector.py", line 737, in _create_direct_connection
aiohttp.client_exceptions.ClientConnectorError: [Errno 22] Can not connect to 192.168.159.128:3080 [œÂ‚˚¯ÂÌ Ú‡ÈÏ‡ÛÚ ÒÂÏ‡ÙÓ‡]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./gns3-server\gns3server\controller\compute.py", line 509, in _run_http_query
  File "C:\Python36-x64\lib\site-packages\aiohttp\helpers.py", line 97, in __iter__
  File "C:\Python36-x64\lib\site-packages\aiohttp\client.py", line 231, in _request
  File "C:\Python36-x64\lib\site-packages\aiohttp\connector.py", line 383, in connect
aiohttp.client_exceptions.ClientConnectorError: [Errno 22] Cannot connect to host 192.168.159.128:3080 ssl:False [Can not connect to 192.168.159.128:3080 [œÂ‚˚¯ÂÌ Ú‡ÈÏ‡ÛÚ ÒÂÏ‡ÙÓ‡]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./gns3-server\gns3server\web\route.py", line 195, in control_schema
  File "./gns3-server\gns3server\handlers\api\controller\compute_handler.py", line 138, in get_forward
  File "./gns3-server\gns3server\controller\compute.py", line 588, in forward
  File "./gns3-server\gns3server\controller\compute.py", line 371, in http_query
  File "./gns3-server\gns3server\controller\compute.py", line 513, in _run_http_query
gns3server.controller.compute.ComputeError: [Errno 22] Cannot connect to host 192.168.159.128:3080 ssl:False [Can not connect to 192.168.159.128:3080 [œÂ‚˚¯ÂÌ Ú‡ÈÏ‡ÛÚ ÒÂÏ‡ÙÓ‡]]
2018-04-13 13:14:05 INFO helpers.py:508 127.0.0.1 - - [13/Apr/2018:10:14:05 +0000] "GET /v2/computes/vm/qemu/binaries HTTP/1.1" 409 513 "-" "GNS3 QT Client v2.1.0"
